// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oms.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CustomerID           string   `protobuf:"bytes,2,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	Items                []*Item  `protobuf:"bytes,4,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_c370aa695928c781, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Order) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	PriceID              string   `protobuf:"bytes,4,opt,name=PriceID,proto3" json:"PriceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_c370aa695928c781, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Item) GetPriceID() string {
	if m != nil {
		return m.PriceID
	}
	return ""
}

type ItemsWithQuantity struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsWithQuantity) Reset()         { *m = ItemsWithQuantity{} }
func (m *ItemsWithQuantity) String() string { return proto.CompactTextString(m) }
func (*ItemsWithQuantity) ProtoMessage()    {}
func (*ItemsWithQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c370aa695928c781, []int{2}
}

func (m *ItemsWithQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsWithQuantity.Unmarshal(m, b)
}
func (m *ItemsWithQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsWithQuantity.Marshal(b, m, deterministic)
}
func (m *ItemsWithQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsWithQuantity.Merge(m, src)
}
func (m *ItemsWithQuantity) XXX_Size() int {
	return xxx_messageInfo_ItemsWithQuantity.Size(m)
}
func (m *ItemsWithQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsWithQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsWithQuantity proto.InternalMessageInfo

func (m *ItemsWithQuantity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ItemsWithQuantity) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	CustomerOd           string               `protobuf:"bytes,1,opt,name=customerOd,proto3" json:"customerOd,omitempty"`
	Items                []*ItemsWithQuantity `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c370aa695928c781, []int{3}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetCustomerOd() string {
	if m != nil {
		return m.CustomerOd
	}
	return ""
}

func (m *CreateOrderRequest) GetItems() []*ItemsWithQuantity {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "api.Order")
	proto.RegisterType((*Item)(nil), "api.Item")
	proto.RegisterType((*ItemsWithQuantity)(nil), "api.ItemsWithQuantity")
	proto.RegisterType((*CreateOrderRequest)(nil), "api.CreateOrderRequest")
}

func init() {
	proto.RegisterFile("oms.proto", fileDescriptor_c370aa695928c781)
}

var fileDescriptor_c370aa695928c781 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0x43, 0x29, 0xbc, 0x2f, 0x83, 0x31, 0x71, 0x0e, 0xb8, 0xe1, 0x80, 0xa4, 0x27, 0x0e,
	0xa6, 0x4d, 0xea, 0x07, 0x30, 0xc1, 0x5e, 0x7a, 0x11, 0x2d, 0x07, 0x13, 0x4f, 0x6e, 0xcb, 0x46,
	0x36, 0xb2, 0x6c, 0xdd, 0x3f, 0x26, 0x7e, 0x7b, 0xc3, 0x58, 0x9a, 0x22, 0xb7, 0x99, 0x67, 0x76,
	0x9e, 0xdf, 0xcc, 0x2c, 0x8c, 0xb4, 0xb2, 0x71, 0x6d, 0xb4, 0xd3, 0xd8, 0xe7, 0xb5, 0x8c, 0x6a,
	0x18, 0xac, 0xcc, 0x46, 0x18, 0xbc, 0x84, 0x20, 0xcf, 0x58, 0x6f, 0xde, 0x5b, 0x8c, 0x8a, 0x20,
	0xcf, 0x70, 0x06, 0x50, 0x79, 0xeb, 0xb4, 0x12, 0x26, 0xcf, 0x58, 0x40, 0x7a, 0x47, 0xc1, 0x09,
	0x0c, 0xd7, 0x8e, 0x3b, 0x6f, 0x59, 0x9f, 0x6a, 0x4d, 0x86, 0x37, 0x30, 0xc8, 0x9d, 0x50, 0x96,
	0x85, 0xf3, 0xfe, 0x62, 0x9c, 0x8e, 0x62, 0x5e, 0xcb, 0xf8, 0xa0, 0x14, 0xbf, 0x7a, 0xf4, 0x06,
	0xe1, 0x21, 0x38, 0x03, 0x22, 0x84, 0x8f, 0x5c, 0x89, 0x06, 0x45, 0x31, 0x4e, 0xe1, 0xff, 0xb3,
	0xe7, 0x7b, 0x27, 0xdd, 0x37, 0x61, 0x06, 0x45, 0x9b, 0x23, 0x83, 0x7f, 0x4f, 0x46, 0x56, 0x22,
	0xcf, 0x58, 0x48, 0x2d, 0xc7, 0x34, 0xba, 0x87, 0x2b, 0x42, 0xbd, 0x48, 0xb7, 0x6d, 0x9f, 0xff,
	0xc5, 0x75, 0xad, 0x83, 0x53, 0xeb, 0xa8, 0x04, 0x7c, 0x30, 0x82, 0x3b, 0x41, 0xa7, 0x29, 0xc4,
	0xa7, 0x17, 0xd6, 0x75, 0x2f, 0xb2, 0xda, 0x34, 0x4e, 0x1d, 0x05, 0x6f, 0x8f, 0x9b, 0x07, 0xb4,
	0xf9, 0xa4, 0xdd, 0xfc, 0x64, 0x90, 0xe6, 0x0c, 0xe9, 0x12, 0x2e, 0xc8, 0x7d, 0x2d, 0xcc, 0x97,
	0xac, 0x04, 0xa6, 0x30, 0xee, 0x30, 0xf1, 0x9a, 0xba, 0xcf, 0xa7, 0x98, 0x02, 0x15, 0x48, 0x5a,
	0xce, 0x5f, 0x67, 0xef, 0xd2, 0x6d, 0x7d, 0x19, 0x57, 0x5a, 0x25, 0x4a, 0xee, 0x76, 0xfe, 0x43,
	0x26, 0x95, 0x56, 0x4a, 0xef, 0x6d, 0xc2, 0x6b, 0x59, 0x0e, 0xe9, 0xab, 0xef, 0x7e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0xa8, 0xf5, 0x5f, 0xf7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/api.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*Order, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oms.proto",
}
